/**
 * Audit Trail Constants
 * 
 * Single source of truth for all Audit Event definitions, severities, and statuses.
 */

export const AUDIT_EVENT_SEVERITY = {
  INFO: "INFO",
  WARNING: "WARNING",
  CRITICAL: "CRITICAL",
} as const

export type AuditEventSeverity = typeof AUDIT_EVENT_SEVERITY[keyof typeof AUDIT_EVENT_SEVERITY]

export const AUDIT_EVENT_STATUS = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
} as const

export type AuditEventStatus = typeof AUDIT_EVENT_STATUS[keyof typeof AUDIT_EVENT_STATUS]

export const AUDIT_ACTIONS = {
  // User Actions
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",

  // Role & Permissions
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // Assignments
  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  ASSIGNMENT_UPDATED: "ASSIGNMENT_UPDATED",
  ASSIGNMENT_DELETED: "ASSIGNMENT_DELETED",
  ASSIGNMENT_TRANSFERRED: "ASSIGNMENT_TRANSFERRED",

  // Authentication & Security
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // Master Data
  MASTER_DATA_CHANGED: "MASTER_DATA_CHANGED",

  // Notifications
  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
  NOTIFICATION_DELETED: "NOTIFICATION_DELETED",

  // Configuration
  SYSTEM_CONFIGURATION_CHANGED: "SYSTEM_CONFIGURATION_CHANGED",
  MONITORING_CONFIGURATION_CHANGED: "MONITORING_CONFIGURATION_CHANGED",

  // Generic
  GENERIC_CREATED: "GENERIC_CREATED",
  GENERIC_UPDATED: "GENERIC_UPDATED",
  GENERIC_DELETED: "GENERIC_DELETED",
  GENERIC_READ: "GENERIC_READ",
  GENERIC_ACTION: "GENERIC_ACTION",
} as const

export type AuditEventAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS]
